name: Update Daily Sync File

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Update daily_sync.txt
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')" > daily_sync.txt

      - name: Commit and push changes
        run: |
          git add daily_sync.txt
          git commit -m "Update daily_sync.txt with today's date and time"
          git push
