name: Daily Update

on:
  schedule:
    - cron: "0 5 * * *"  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes
        run: |
          echo "Last run: $(date)" > update_log.txt  # Example update
          git add update_log.txt
          git commit -m "Daily update: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
