name: Update README

on:
  schedule:
    - cron: "25 17 * * *"  # Runs daily at 17:25 UTC (but we'll adjust for PST/PDT)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          # Set the timezone to America/Los_Angeles
          TZ=America/Los_Angeles date "+%Y-%m-%d %H:%M %Z" # example of setting timezone

          # or you can use `timedatectl` to set the timezone on the runner.
          sudo timedatectl set-timezone 'America/Los_Angeles'

          echo "Last updated: $(date +'%Y-%m-%d %H:%M %Z')" >> README.md
          # or use sed with proper markers
          # sed -i "s/Last updated:.*/Last updated: $(date +'%Y-%m-%d %H:%M %Z')/g" README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated README: $(date +'%Y-%m-%d %H:%M %Z')"
          file_pattern: README.md
