name: Update README

on:
  schedule:
    - cron: "31 17 * * *"  # Runs daily at 18:02 UTC (9:25 AM PST/PDT)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timezone and update README
        run: |
          # Set timezone for this session
          export TZ=America/Los_Angeles

          # Define the timestamp
          TIMESTAMP="Last updated: $(date +'%Y-%m-%d %H:%M %Z')"

          # Ensure the target line exists before replacing
          if grep -q "Last updated:" README.md; then
            sed -i "s/Last updated:.*/$TIMESTAMP/g" README.md
          else
            echo "$TIMESTAMP" >> README.md
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated README: $(date +'%Y-%m-%d %H:%M %Z')"
          file_pattern: README.md
