name: Frequent Update

on:
  schedule:
    - cron: "*/5 * * * *"  # Attempt to run every minute (may be throttled)
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Fixes push permission issues

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes
        run: |
          echo "Last run: $(date)" > update_log.txt  # Example update
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add update_log.txt
          git commit -m "Frequent update: $(date)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
